server:
  port: 8080

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/mydb
    username: biz
    password: 162458
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none  # ?? update, create, create-drop ?
    show-sql: true
    properties:
      hibernate:
        format_sql: true

