server:
  port: 8080

spring:
  datasource:
#    url: jdbc:mariadb://my-mariadb:3306/mydb
    url: jdbc:mariadb://localhost:3306/mydb
    username: biz
    password: 162458
    driver-class-name: org.mariadb.jdbc.Driver
  devtools:
    restart:
      enabled: true
      poll-interval: 1000ms

  jpa:
    hibernate:
      ddl-auto: none  # ?? update, create, create-drop ?
    show-sql: true
    properties:
      hibernate:
        format_sql: true

docker:
  image-name: "comment-job-runner-image"

jwt:
  secret_key: "nbcp-secret-key"

