version: "3.8"

services:
  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    command: ./gradlew bootRun
#    environment:
    networks:
      - mynetwork

networks:
  mynetwork:
    external: true  # 이미 존재하는 네트워크 사용